Code Review Request for To Do list: interactive list
jose-Abel/todo-list pull request #2
Opened 2021-09-22 19:57 UTC by jose-Abel

Hello, 
I'm requesting a code review for the Day 3 of this ES6 and Webpack week where it was requested the following:
- New JavaScript files and import it as a module that it will contain methods related to the status updates (completed: true / false). In my implementation is called changeStatus.js
- Event listeners to the checkboxes that detects the change event.
- Update items object's value for completed key upon user actions.
- Store the updated array of items in local storage, so the user gets the correct list values after the page reloads.

Hoping to get an amazing feedback, happy coding.

2021-09-22 20:35 UTC, Dipeshtwis requested changes
Hi @jose-Abel, 

:+1: This is good to make it this far, your project is really nice, congratulations on the good work you have done so far.
:+1: It has an event listener on the checkbox (change).

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


 ## Required Changes ♻️

**_Check the comments under the review_**

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

- N.A.

Cheers and Happy coding!👏👏👏
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**_Dipesh Kumar_**


------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project(check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-09-22 20:35 UTC, Dipeshtwis commented on src/index.js
- [ ] When I mark one task is completed and then I refresh the page, All the task looks like before instead of one task completed. Make sure you updated the UI as well.

2021-09-22 20:35 UTC, Dipeshtwis commented on src/changeStatus.js
> +/* eslint-disable func-names */
- [ ] Please do not disable linters, Instead, try to implement the best practices. in code.

2021-09-23 03:09 UTC, addod19 approved these changes
### Hi @jose-Abel, 

Your project is complete!  Disabling inline linters removed :+1: Tasks stay marked even after page reload :fireworks: There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-09-23 03:10 UTC, addod19 commented on src/changeStatus.js
> +/* eslint-disable func-names */
### Optional
- [ ] It would be better if we center our content

2021-09-23 10:08 UTC, merged